# Generated by Django 3.1a1 on 2020-06-04 14:31

import dirtyfields.dirtyfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("dol_id", models.CharField(max_length=255)),
                ("pub_date", models.DateTimeField(null=True)),
                ("scraped", models.BooleanField(default=False)),
                ("scraped_data", models.JSONField()),
                ("pdf", models.FileField(upload_to="job_pdfs/")),
            ],
            options={"abstract": False,},
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
