# Generated by Django 3.1a1 on 2020-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticValue",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
