# Generated by Django 3.1a1 on 2020-06-09 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_staticvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="first_seen",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="last_seen",
            field=models.DateField(auto_now_add=True),
        ),
    ]
