# Generated by Django 3.2.6 on 2021-08-06 11:47

from django.db import migrations


class Migration(migrations.Migration):
    def clean_listings(apps, schema_editor):
        Listing = apps.get_model("listings", "Listing")
        listings_to_clean = Listing.objects.filter(scraped=True)

        for l in listings_to_clean:
            if not l.scraped_data:
                continue

            old_url = l.scraped_data["apply_url"]
            l.clean()
            if old_url != l.scraped_data["apply_url"]:
                l.save()

    dependencies = [
        ("listings", "0004_tweak_scraped_data_field"),
    ]

    operations = [migrations.RunPython(clean_listings)]
