# Generated by Django 3.2.7 on 2021-11-22 08:34

from django.db import migrations


class Migration(migrations.Migration):
    def delete_invalid_dol_ids(apps, schema_editor):
        Listing = apps.get_model("listings", "Listing")
        Listing.objects.exclude(dol_id__startswith="H-").delete()

    dependencies = [
        ("listings", "0005_clean_url_field"),
    ]

    operations = [migrations.RunPython(delete_invalid_dol_ids)]
